### ISSUE TITLE
OpenImageIO crashing with EXR sequence when trying to get PixelAspectRatio attribute

### ISSUE THREAD

**Issue by GreenEminence** [OpenImageIO/oiio#2268]
### Problem
*Sorry for the misleading title - it's a sequence of TIFFs*
When trying to obtain PixelAspectRatio attribute from a sequence of TIFF files, OpenImageIO calls libtiff -> tagCompare() method which is causing application to crash.

Here's the back trace from gdb:
```#0  0x00007fd35df09b03 in tagCompare () from /lib64/libtiff.so.5
#1  0x00007fd4070f6b08 in bsearch () from /lib64/libc.so.6
#2  0x00007fd35df09db4 in TIFFFindField () from /lib64/libtiff.so.5
#3  0x00007fd35f5b55d8 in OpenImageIO_v1_8::TIFFInput::find_tag(int, TIFFDataType, OpenImageIO_v1_8::string_view) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#4  0x00007fd35f5afd2d in OpenImageIO_v1_8::TIFFInput::readspec(bool) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#5  0x00007fd35f5b228e in OpenImageIO_v1_8::TIFFInput::seek_subimage(int, int, OpenImageIO_v1_8::ImageSpec&) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#6  0x00007fd35f5b2b43 in OpenImageIO_v1_8::TIFFInput::open(std::string const&, OpenImageIO_v1_8::ImageSpec&, OpenImageIO_v1_8::ImageSpec const&) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#7  0x00007fd35fdcfc75 in OpenImageIO_v1_8::pvt::ImageCacheFile::open(OpenImageIO_v1_8::pvt::ImageCachePerThreadInfo*) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#8  0x00007fd35fdd3033 in OpenImageIO_v1_8::pvt::ImageCacheImpl::verify_file(OpenImageIO_v1_8::pvt::ImageCacheFile*, OpenImageIO_v1_8::pvt::ImageCachePerThreadInfo*, bool) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#9  0x00007fd35fdd4f5d in OpenImageIO_v1_8::pvt::ImageCacheImpl::get_image_info(OpenImageIO_v1_8::pvt::ImageCacheFile*, OpenImageIO_v1_8::pvt::ImageCachePerThreadInfo*, int, int, OpenImageIO_v1_8::ustring, OpenImageIO_v1_8::TypeDesc, void*) () from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#10 0x00007fd35fdcf13a in OpenImageIO_v1_8::pvt::ImageCacheImpl::get_image_info(OpenImageIO_v1_8::ustring, int, int, OpenImageIO_v1_8::ustring, OpenImageIO_v1_8::TypeDesc, void*) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#11 0x00007fd35f65d921 in OpenImageIO_v1_8::ImageBufImpl::init_spec(OpenImageIO_v1_8::string_view, int, int) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#12 0x00007fd35f65f466 in OpenImageIO_v1_8::ImageBufImpl::read(int, int, int, int, bool, OpenImageIO_v1_8::TypeDesc, bool (*)(void*, float), void*) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#13 0x00007fd35f66108e in OpenImageIO_v1_8::ImageBufImpl::ImageBufImpl(OpenImageIO_v1_8::string_view, int, int, OpenImageIO_v1_8::ImageCache*, OpenImageIO_v1_8::ImageSpec const*, void*, OpenImageIO_v1_8::ImageSpec const*) () from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#14 0x00007fd35f661353 in OpenImageIO_v1_8::ImageBuf::ImageBuf(OpenImageIO_v1_8::string_view, int, int, OpenImageIO_v1_8::ImageCache*, OpenImageIO_v1_8::ImageSpec const*) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/libOpenImageIO.so.1.8
#15 0x00007fd37894d2f7 in boost::python::objects::make_holder<1>::apply<boost::python::objects::value_holder<OpenImageIO_v1_8::ImageBuf>, boost::mpl::vector1<std::string const&> >::execute(_object*, std::string const&) () from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/python2.7/site-packages/OpenImageIO.so
#16 0x00007fd3789539cf in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(_object*, std::string const&), boost::python::default_call_policies, boost::mpl::vector3<void, _object*, std::string const&> > >::operator()(_object*, _object*) ()
   from .../1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/oiio/1.8.13/lib64/python2.7/site-packages/OpenImageIO.so
#17 0x00007fd35f25ce1a in boost::python::objects::function::call(_object*, _object*) const ()
   from ...//1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/boost/1.55.0/lib/libboost_python.so.1.55.0
#18 0x00007fd35f25d188 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
   from ...//1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/boost/1.55.0/lib/libboost_python.so.1.55.0
#19 0x00007fd35f266a03 in boost::python::handle_exception_impl(boost::function0<void>) ()
   from ...//1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/boost/1.55.0/lib/libboost_python.so.1.55.0
#20 0x00007fd35f25ba93 in function_call () from ...//1.3/CentOS_Linux_7.4.1708/gcc4.8.5_glibc2.17_x86_64/CY2014/boost/1.55.0/lib/libboost_python.so.1.55.0
#21 0x00007fd40cad2c13 in PyObject_Call () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#22 0x00007fd40cae161d in ?? () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#23 0x00007fd40cad2c13 in PyObject_Call () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#24 0x00007fd40cb3e1ff in ?? () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#25 0x00007fd40cb3cd8f in ?? () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#26 0x00007fd40cad2c13 in PyObject_Call () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#27 0x00007fd40cb87764 in PyEval_EvalFrameEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#28 0x00007fd40cb8ad1e in PyEval_EvalFrameEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#29 0x00007fd40cb8ad1e in PyEval_EvalFrameEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#30 0x00007fd40cb8d1fd in PyEval_EvalCodeEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#31 0x00007fd40cb04700 in ?? () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#32 0x00007fd40cad2c13 in PyObject_Call () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#33 0x00007fd40cad3749 in PyObject_CallFunctionObjArgs () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#34 0x00007fd40cb1f221 in _PyObject_GenericGetAttrWithDict () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#35 0x00007fd40cb883cb in PyEval_EvalFrameEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#36 0x00007fd40cb8ad1e in PyEval_EvalFrameEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#37 0x00007fd40cb8ad1e in PyEval_EvalFrameEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#38 0x00007fd40cb8ad1e in PyEval_EvalFrameEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#39 0x00007fd40cb8d1fd in PyEval_EvalCodeEx () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#40 0x00007fd40cb04700 in ?? () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
#41 0x00007fd40cad2c13 in PyObject_Call () from .../TweakSoftware/rv-Linux-x86-64-7.2.1/lib/libpython2.7.so
```

**Expected behavior:**  
Get the floating point value of the image' pixel aspect ratio

**Actual behavior:**
OpenImageIO is causing application to crash.

### Steps to Reproduce

Run the following code:
```
import OpenImageIO as oiio
buf = oiio.ImageBuf(str(path))
pixel_aspect = buf.spec().get_float_attribute("PixelAspectRatio", 0.0)
if pixel_aspect == 0.0:
    pixel_aspect = None
```

### Versions

* OIIO branch/version: 1.8.13
* OS: Centos7.4
* C++ compiler: gcc4.8.5 glibc 2.17

**Comment by lgritz** [comment]
Does this fail on ALL tiff files? Only on some? Can you attach or email me a minimal TIFF file that this will crash for?

Are you by any chance able to test on either the release branch (2.0.8 is the latest supported release) or the master branch, and does it crash there as well?

**Comment by GreenEminence** [comment]
I believe our version of OIIO was linked against incorrect version of libtiff, everything works with the latest build.
